{{- if .Values.ui.ingress.enabled -}}
{{- include "linha.ui.ingress.validate" . -}}
{{- $name := include "linha.name" . -}}
{{- $host := include "linha.ui.ingress.host" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ui" $name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: linha
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: ui
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ui.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.ui.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range list "/ui" "/v1/admin" }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
          {{- end }}
{{- end }}
