package telemetry

type Family struct {
	Kind, Scope, Help string
	Labels            []string
}

var Catalog = map[string]Family{
	"linha_client_leases":                                  {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Current stored lease generations: active, expired, released; active uses database-clock expiry."},
	"linha_client_lease_events_total":                      {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "event"}, Help: "Acquired, explicitly released, or expired generations, once per event/generation. Renewals do not count as acquisitions."},
	"linha_context_versions":                               {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Immutable versions in each normalized lifecycle state."},
	"linha_context_versions_with_demand":                   {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "demand"}, Help: "Versions with live clients or accepted work, reported separately as clients|work; one version can have both, so do not sum these as distinct versions."},
	"linha_context_conditions":                             {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "reason"}, Help: "Versions with a provisioning/lifecycle condition, grouped by fixed platform reason."},
	"linha_metrics_context_labels":                         {Kind: "gauge", Scope: "S", Labels: []string{"state"}, Help: "Number of permanently assigned named dimensions and logical contexts grouped into overflow."},
	"linha_job_records":                                    {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Retained jobs currently in QUEUED, RETRYING, RUNNING, CANCELLING, SUCCEEDED, FAILED, CANCELLED; terminal values include retained history."},
	"linha_queue_jobs":                                     {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "eligibility"}, Help: "Queued/retrying work classified ready|backoff; never includes running work."},
	"linha_queue_oldest_age_seconds":                       {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context"}, Help: "Age since original submission of oldest QUEUED/RETRYING job, including retry backoff; zero for an empty queue."},
	"linha_job_submissions_total":                          {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "source"}, Help: "Newly committed jobs (sdk|admin), excluding idempotent repeats."},
	"linha_job_completions_total":                          {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "outcome"}, Help: "First committed terminal job transitions: SUCCEEDED, FAILED, CANCELLED."},
	"linha_job_failures_total":                             {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "reason"}, Help: "Terminal FAILED jobs classified by bounded reason; business exception text never becomes a label."},
	"linha_job_retries_total":                              {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "reason"}, Help: "Persisted additional-attempt decisions, not duplicate claim attempts."},
	"linha_attempts_current":                               {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Nonterminal current attempts with running|cancelling|lease_expired, a disjoint classification."},
	"linha_attempt_completions_total":                      {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "outcome"}, Help: "First persisted attempt termination, including failure/interruption/cancellation; duplicate completion callbacks excluded."},
	"linha_job_queue_wait_seconds":                         {Kind: "histogram", Scope: "S", Labels: []string{"engine", "context"}, Help: "Submission to first assignment, exactly one observation when first claimed."},
	"linha_attempt_duration_seconds":                       {Kind: "histogram", Scope: "S", Labels: []string{"engine", "context"}, Help: "Assignment to persisted terminal attempt state, exactly one observation per terminated attempt."},
	"linha_job_duration_seconds":                           {Kind: "histogram", Scope: "S", Labels: []string{"engine", "context", "outcome"}, Help: "Submission to terminal job outcome, including retries and queue wait."},
	"linha_job_cancellation_duration_seconds":              {Kind: "histogram", Scope: "S", Labels: []string{"engine", "context"}, Help: "First cancellation intent to CANCELLED; success-before-cancel is excluded."},
	"linha_worker_updates_rejected_total":                  {Kind: "counter", Scope: "L", Labels: []string{"operation", "reason"}, Help: "Rejected worker reports; operations are a fixed set and reasons include identity mismatch, stale attempt, expired lease, invalid state, invalid payload, and other."},
	"linha_accounting_started_timestamp_seconds":           {Kind: "gauge", Scope: "S", Labels: []string{}, Help: "Baseline of new durable lifecycle counters/histograms; old history is represented by gauges, not fabricated events."},
	"linha_workers":                                        {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Registered workers classified ready|draining|stale; stale takes precedence over draining."},
	"linha_worker_capacity_slots":                          {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context"}, Help: "Total configured claim slots on fresh non-draining registered workers."},
	"linha_worker_occupied_slots":                          {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context"}, Help: "Slots held by unexpired current running/cancelling attempts on those workers; unrelated/stale instances are excluded."},
	"linha_engine_instances":                               {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Managed instances by lifecycle state, including STARTING, READY, DRAINING, DEAD."},
	"linha_engine_desired_instances":                       {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context"}, Help: "Current desired instance count after client/work lifetime and scaler rules, not just configured minimum."},
	"linha_engine_configured_instances":                    {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "bound"}, Help: "Sum of configured min|max for versions with current demand; stopped versions do not inflate limits."},
	"linha_engine_provisioning_duration_seconds":           {Kind: "histogram", Scope: "S", Labels: []string{"engine", "context"}, Help: "Instance demand to first ready registered worker, boundaries 1, 5, 15, 30, 60, 120, 300, 600, 1800, +Inf."},
	"linha_engine_instances_replaced_total":                {Kind: "counter", Scope: "S", Labels: []string{"engine", "context", "reason"}, Help: "Persisted replacement decisions for lost/failed instances; reconciliation polls are not new events."},
	"linha_engine_observations":                            {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "state"}, Help: "Required live-instance observations classified fresh|stale|missing, measured independently of their content."},
	"linha_engine_observation_oldest_timestamp_seconds":    {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context"}, Help: "Oldest observation among currently required observed instances; missing observations are indicated separately."},
	"linha_spark_driver_pods":                              {Kind: "gauge", Scope: "O", Labels: []string{"engine", "context", "state"}, Help: "Current owned Spark driver pods by normalized Kubernetes phase, separate from SDK readiness."},
	"linha_spark_executor_pods":                            {Kind: "gauge", Scope: "O", Labels: []string{"engine", "context", "state"}, Help: "Current owned executor pods by phase; deleted executors disappear."},
	"linha_spark_executor_configuration":                   {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "bound"}, Help: "Sum of configured executor min|initial|max across currently desired drivers; static instances use the same value for all three."},
	"linha_spark_pod_cpu_cores":                            {Kind: "gauge", Scope: "O", Labels: []string{"engine", "context", "role", "allocation"}, Help: "Sum of Spark main-container CPU requests/limits; role driver/executor, allocation request/limit."},
	"linha_spark_pod_memory_bytes":                         {Kind: "gauge", Scope: "O", Labels: []string{"engine", "context", "role", "allocation"}, Help: "Sum of observed Spark main-container memory requests/limits, including container overhead; not memory usage."},
	"linha_server_build_info":                              {Kind: "gauge", Scope: "L", Labels: []string{"version", "revision"}, Help: "Build metadata, once per responding server."},
	"linha_server_ready":                                   {Kind: "gauge", Scope: "L", Labels: []string{}, Help: "Latest bounded readiness observation, 0/1; timestamped by its collector."},
	"linha_servers":                                        {Kind: "gauge", Scope: "S", Labels: []string{"state"}, Help: "Latest process per server pod classified ready|unready|stale|stopping, with 24-hour heartbeat retention."},
	"linha_dependency_available":                           {Kind: "gauge", Scope: "L", Labels: []string{"dependency"}, Help: "Latest configured database/local-storage check; 0/1, never fabricated for an unchecked service."},
	"linha_background_loop_runs_total":                     {Kind: "counter", Scope: "L", Labels: []string{"loop", "outcome"}, Help: "Runs of reconcile/recovery/retention/cleanup/heartbeat/observation, success/error."},
	"linha_background_loop_duration_seconds":               {Kind: "histogram", Scope: "L", Labels: []string{"loop"}, Help: "Duration of each loop run, including errors."},
	"linha_background_loop_last_success_timestamp_seconds": {Kind: "gauge", Scope: "L", Labels: []string{"loop"}, Help: "Last success; zero before the first success."},
	"linha_database_pool_connections":                      {Kind: "gauge", Scope: "L", Labels: []string{"state"}, Help: "Acquired, idle, constructing connections."},
	"linha_database_pool_max_connections":                  {Kind: "gauge", Scope: "L", Labels: []string{}, Help: "Configured pool capacity."},
	"linha_database_pool_acquire_wait_seconds_total":       {Kind: "counter", Scope: "L", Labels: []string{}, Help: "Accumulated pool acquisition wait time."},
	"linha_database_pool_acquire_failures_total":           {Kind: "counter", Scope: "L", Labels: []string{"reason"}, Help: "Timeout/cancel/error acquisition failures."},
	"linha_kubernetes_api_requests_total":                  {Kind: "counter", Scope: "L", Labels: []string{"resource", "verb", "outcome"}, Help: "Bounded resource/verb set and outcome success/forbidden/not_found/timeout/error."},
	"linha_kubernetes_api_duration_seconds":                {Kind: "histogram", Scope: "L", Labels: []string{"resource", "verb"}, Help: "Kubernetes call latency without names, selectors, URLs, or error strings."},
	"linha_collector_success":                              {Kind: "gauge", Scope: "L", Labels: []string{"collector"}, Help: "Latest collection completed successfully, 0/1."},
	"linha_collector_last_success_timestamp_seconds":       {Kind: "gauge", Scope: "L", Labels: []string{"collector"}, Help: "Last usable sample time; zero before initialization."},
	"linha_collector_duration_seconds":                     {Kind: "histogram", Scope: "L", Labels: []string{"collector"}, Help: "Background collection latency."},
	"linha_collector_errors_total":                         {Kind: "counter", Scope: "L", Labels: []string{"collector", "reason"}, Help: "Bounded timeout/unavailable/invalid/other errors."},
	"linha_api_requests_total":                             {Kind: "counter", Scope: "L", Labels: []string{"route", "method", "status_code"}, Help: "All API responses, including unauthorized, worker and admin routes, and unmatched paths; probes, metrics and static assets are excluded."},
	"linha_api_request_duration_seconds":                   {Kind: "histogram", Scope: "L", Labels: []string{"route", "method"}, Help: "Time through response completion, including streamed results."},
	"linha_api_requests_in_flight":                         {Kind: "gauge", Scope: "L", Labels: []string{"route", "method"}, Help: "Currently executing API requests."},
	"linha_api_response_bytes_total":                       {Kind: "counter", Scope: "L", Labels: []string{"route", "method"}, Help: "Bytes written by API responses."},
	"linha_results":                                        {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "provider", "destination", "state"}, Help: "Published result sets classified retained/expired, not per-file parts."},
	"linha_result_published_bytes":                         {Kind: "gauge", Scope: "S", Labels: []string{"engine", "context", "provider", "destination", "state"}, Help: "Logical published file/part bytes recorded in manifests; exclude manifest bytes from dataset part totals and do not count replicas/staging copies."},
	"linha_result_cleanup_candidates":                      {Kind: "gauge", Scope: "S", Labels: []string{"provider", "destination"}, Help: "Allocations currently eligible under terminal/expiry/delegation/grace rules."},
	"linha_result_cleanup_runs_total":                      {Kind: "counter", Scope: "L", Labels: []string{"provider", "destination", "outcome"}, Help: "Cleanup executions success/error; these are operations, not exactly-once object deletion counts."},
	"linha_storage_operations_total":                       {Kind: "counter", Scope: "L", Labels: []string{"provider", "destination", "operation", "outcome"}, Help: "Server-observed allocate/upload/download/publish/list/delete/delegate/probe/other operations."},
	"linha_storage_operation_duration_seconds":             {Kind: "histogram", Scope: "L", Labels: []string{"provider", "destination", "operation"}, Help: "Complete server-observed operation latency."},
	"linha_storage_transferred_bytes_total":                {Kind: "counter", Scope: "L", Labels: []string{"provider", "destination", "direction"}, Help: "Server-observed upload/download bytes; direct worker/Spark S3 writes are excluded."},
	"linha_staging_reserved_bytes":                         {Kind: "gauge", Scope: "L", Labels: []string{}, Help: "Current server staging budget reservation."},
	"linha_staging_limit_bytes":                            {Kind: "gauge", Scope: "L", Labels: []string{}, Help: "Configured server staging reservation limit."},
}
