<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.k3rnl</groupId>
    <artifactId>linha-jvm</artifactId>
    <version>0.1.1-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>linha-spark_2.12</artifactId>
  <properties>
    <spark.version>3.5.6</spark.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.k3rnl</groupId>
      <artifactId>linha-worker_2.12</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_2.12</artifactId>
      <version>${spark.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED</argLine>
          <environmentVariables>
            <SPARK_LOCAL_HOSTNAME>127.0.0.1</SPARK_LOCAL_HOSTNAME>
          </environmentVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
