import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    {
      name: "keep-embed-source",
      generateBundle() {
        this.emitFile({
          type: "asset",
          fileName: ".keep",
          source:
            "Frontend build assets are generated by npm run build in web/.\n",
        });
      },
    },
  ],
  base: "/ui/",
  build: { outDir: "../server/internal/webui/assets", emptyOutDir: true },
  server: {
    proxy: {
      "/v1": "http://127.0.0.1:8080",
      "/ui/config": "http://127.0.0.1:8080",
      "/ui/oidc": "http://127.0.0.1:8080",
    },
  },
});
